# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
orbs:
  docker: circleci/docker@1.5.0

version: 2
on:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile'
      - 'app/**'
      - '.github/**'

jobs:
  docker-steps:
    docker:
      - image: circleci/docker@1.5.0
    steps:
      - run:
         command: |
           cd ./project-ml-microservice-kubernetes
           ./upload_docker.sh
           ./run_docker.sh

  build:
    docker:
      - image: python:3.7.3-stretch
    working_directory: ~/project-ml-microservice-kubernetes
    steps:
      - checkout
      # Download and cache dependencies
      - run:
         command:  cd ./project-ml-microservice-kubernetes
      - restore_cache:
          keys:
           
            - v1-dependencies-{{ checksum "./project-ml-microservice-kubernetes/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv ~/.devops
            source ~/.devops/bin/activate
            cd ./project-ml-microservice-kubernetes
            ls -l
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "./project-ml-microservice-kubernetes/requirements.txt" }}
      - run:
          name: run lint
          command: |
            cd ./project-ml-microservice-kubernetes/
            pip install --upgrade pip && python3 -m pip install pylint --no-cache-dir
            pip install -r requirements.txt
            make lint