
# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
orbs:
  docker: circleci/docker@1.5.0
  aws-cli: circleci/aws-cli@1.3.0

version: 2.1

jobs:
  docker-steps:
    docker:
      - image: docker:17.05.0-ce-git
      #executor: docker/docker
    steps:
      - checkout
      - run:
         name: docker
         command:
            cd project-ml-microservice-kubernetes
            ./upload_docker.sh
            ./run_docker.sh
            service docker status
            docker stack deploy --compose-file compose.yml mystack
      - run:
         name: kubernetes
         command: |
           cd project-ml-microservice-kubernetes
           #service docker status
           #docker stack deploy --compose-file compose.yml mystack
            

  build:
       docker:
        - image: python:3.7.3-stretch
       working_directory: ~/project-ml-microservice-kubernetes
       steps:
         - checkout
      # Download and cache dependencies
         - run:
            command:  cd ./project-ml-microservice-kubernetes
         - restore_cache:
            keys:
             - v1-dependencies-{{ checksum "./project-ml-microservice-kubernetes/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
             - v1-dependencies-

         - run:
             name: install dependencies
             command: |
              python3 -m venv ~/.devops
              source ~/.devops/bin/activate
              cd ./project-ml-microservice-kubernetes
              ls -l
              make install
            # Install hadolint
                       
         - save_cache:
             paths:
             - ./venv
             key: v1-dependencies-{{ checksum "./project-ml-microservice-kubernetes/requirements.txt" }}

         - run:
            name: run lint
            command: |
             cd ./project-ml-microservice-kubernetes/
             pip install --upgrade pip && python3 -m pip install pylint --no-cache-dir
             pip install -r requirements.txt
             make lint

  kubernetes :
      docker:
            # Docker image here that supports AWS CLI
      - image: cimg/base:2020.01
      steps:
            # Checkout code from git
            - checkout
            - aws-cli/setup
            - run:
                  name: Creating an Amazon EKS cluster
                  command: |
                   aws eks create-cluster \
                   --region us-east-2 \
                   --name kubernetes-cluster \
                   --kubernetes-version <1.19> \
                   --role-arn <arn:aws:iam::111122223333:role/eks-service-role-AWSServiceRoleForAmazonEKS-EXAMPLEBKZRQR> \
                   --resources-vpc-config subnetIds=<subnet-a9189fe2>,<subnet-50432629>,securityGroupIds=<sg-f5c54184>




workflows:
  default:
    jobs:
      #- docker-steps
      #- build
      - kubernetes 
        

